- name: Allan
  image: ./assets/images/hosts/allan.jpg
  geeklist_id: 355840
  bio: >
    Been playing for 10+ years. Likes clever two-player games and big group chaos. Always brings something weird and wonderful.

- name: Graham
  image: ./assets/images/hosts/graham.jpg
  geeklist_id: 355830
  bio: >
    Strategy lover and spreadsheet wrangler. Always has a pun at the ready and a rulebook memorised.

- name: Rachel & Dom
  image: ./assets/images/hosts/rachel_dom.jpg
  geeklist_id: 355820
  bio: >
    Dream team duo who love co-ops and chaos. Will bring cake *and* competition.

- name: Phil
  image: ./assets/images/hosts/phil.jpg
  geeklist_id: 355850
  bio: >
    Big fan of party games, bluffing, and helping newcomers feel at home. Probably brought too many games again.

