- name: Allan
  image: ./assets/images/hosts/allan.jpg
  geeklist_id: 
  bio: >
    Been playing for 10+ years. Likes clever two-player games and big group chaos. Always has a pun at the ready and a rulebook memorised.

- name: Graham
  image: ./assets/images/hosts/graham.jpg
  geeklist_id: 
  bio: >
    Strategy lover and spreadsheet wrangler. Always brings something weird and wonderful.

- name: Rachel & Dom
  image: ./assets/images/hosts/rachel_dom.jpg
  geeklist_id: 
  bio: >
    Dream team duo who love themed games and chaos.

- name: Phil
  image: ./assets/images/hosts/phil.jpg
  geeklist_id: 355850
  bio: >
    Big fan strategy games but doesn't like games that go on for too long! Loves helping newcomers feel at home. Probably brought too many games again.

