name: Block Protected File Changes

on:
  pull_request:
    paths:
      - 'CNAME'
      - '.gitignore'
      - '.gitattributes'
      - '.github/workflows/**'

jobs:
  prevent-protected-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Check for protected file modifications
        run: |
          echo "❌ This PR modifies protected files (CNAME, .gitignore, workflows, etc.)."
          echo "These files are managed only within the production repo and must not be changed via PRs."
          exit 1
