name: Warn on sensitive files in PR

on: [pull_request]

jobs:
  check-sensitive-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR contents
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full history is available for SHA diffing

      - name: Look for sensitive files in the PR
        run: |
          FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
          SENSITIVE_FILES=$(echo "$FILES" | grep -E '^CNAME$|^\.gitignore$|^\.github/workflows/')

          if [ -n "$SENSITIVE_FILES" ]; then
            echo "⚠️ Sensitive files changed in PR:"
            echo "$SENSITIVE_FILES"

            echo "" >> $GITHUB_STEP_SUMMARY
            echo "### ⚠️ Sensitive Files Changed" >> $GITHUB_STEP_SUMMARY
            echo "$SENSITIVE_FILES" | sed 's/^/- /' >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "Please double-check these changes before merging." >> $GITHUB_STEP_SUMMARY
          else
            echo "✅ No sensitive files found in PR."
          fi
