name: Warn on Sensitive File Changes

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-sensitive-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Comment on PR if sensitive files are changed
        uses: actions/github-script@v6
        with:
          script: |
            const files = await github.rest.pulls.listFiles({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });

            const sensitiveFiles = files.data.filter(f =>
              ['CNAME', '.github/workflows/deploy-to-preview.yml', '.gitignore'].includes(f.filename)
            );

            if (sensitiveFiles.length > 0) {
              const fileList = sensitiveFiles.map(f => `- \`${f.filename}\``).join('\n');
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: `⚠️ **Heads up!**\n\nThis pull request modifies the following sensitive file(s):\n${fileList}\n\nThese are managed carefully and may affect deployment workflows or domain setup. Please double-check before merging.`
              });
            }
