name: Warn on _site folder in PR

on: [pull_request]

jobs:
  check-site-folder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR contents
        uses: actions/checkout@v3

      - name: Look for _site folder in the PR
        run: |
          if git diff --name-only origin/main...HEAD | grep '^_site/'; then
            echo "🚫 Error: PR includes files from the _site/ directory!"
            echo "_site/ is a build folder and should not be committed." >> $GITHUB_STEP_SUMMARY
            exit 1
          else
            echo "✅ No _site/ files found in PR."
          fi
